{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.testplugin",
    "module": "testplugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "testplugin-1.0.0.jar",
          "url": "testplugin-1.0.0.jar",
          "size": 28985,
          "sha512": "993f83f25026cb38541873113008daa8439a0b31c7964339b2d26c8343609c7d8c2db9738c84f5b047ef6b1df8ef29663a7447b6d7cbd301ff07b778a5515a82",
          "sha256": "2faa89c5faafe0eb2345c265657006b0c0fee1df79c5852643aa064b60cec07f",
          "sha1": "32f7c5541caa161d22906544e02dabd7a85ba695",
          "md5": "a09ab746746ddd348983310272901f7c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "testplugin-1.0.0.jar",
          "url": "testplugin-1.0.0.jar",
          "size": 28985,
          "sha512": "993f83f25026cb38541873113008daa8439a0b31c7964339b2d26c8343609c7d8c2db9738c84f5b047ef6b1df8ef29663a7447b6d7cbd301ff07b778a5515a82",
          "sha256": "2faa89c5faafe0eb2345c265657006b0c0fee1df79c5852643aa064b60cec07f",
          "sha1": "32f7c5541caa161d22906544e02dabd7a85ba695",
          "md5": "a09ab746746ddd348983310272901f7c"
        }
      ]
    }
  ]
}
